# Config file for q vs g jet classification
event_type: 'photoproduction'
classes: 'transverse QCDC_longitudinal QCDC_transverse PGF_longitudinal PGF__qq --> qq_qqbar --> qqbar_qqbar --> gg_gg --> qqbar_gg --> gg_qg --> qg' # The double underscore specifies the two classes to consider

leading_jet_pt_min: 8.
subleading_jet_pt_min: 5. 
particle_input: ['leading+subleading']    # Loop over different sets of input particles: leading jet, leading+subleading jets, all particles
kappa: [0.3, 0.5, 0.7]

# Train multiple models with different particle min pt (in GeV) (only implemented for PFNs and single jet observables)
particle_pt_min_list: [0, 0.2, 0.4]

# Input files of training data
#
# 20220926: 2B events, with 6M jets for 5 GeV leading jet pt cut
#     Notes:
#       - Require the leading jet to have pT > 5 GeV
#       - Find up to three jets with pT cuts for the second and third leading jet to be > 2 GeV, in order to allow us to make cuts to select good two-jet events
#       - Jets are made out of running clustering algorithms on particles with pT > 0.1 GeV and -4 < eta < 4 (realistic coverage at EIC?)
#       - All the radiations outside the first and second leading jet (but allowed to be part of the third leading jet) are reported with the jet column value = -1. The radiations are required to be in -4 < eta < 4 and have pT > 0.1.
#       - All particles’ eta and phi are reported with respect to the leading jet rapidity and phi.
#       - It is hard to remove the scattered lepton, so I try to grab it by asking the analysis code to remove electron with longitudinal momentum along the beam larger than 5 GeV. I do not know how efficient this is, but I think it should work pretty well with small Q2.
#       - For the processes with same final parton flavors [13, 68 (gg) and 11, 12, 53, 135, 136 (qqbar)], I assign jet flavors accordingly from this information. For the processes with the mixed parton flavors [28, 131, 132] (qg), I determine the jet flavors by the flavor of the hardest parton in the jet. The hardest parton method sometimes does not match the expected jet flavor, so depending on the statistics, I would try running without processes 28, 131, 132.

input_files:
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/0.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/1.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/2.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/3.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/4.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/5.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/6.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/7.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/8.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/9.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/10.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/11.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/12.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/13.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/14.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/15.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/16.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/17.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/18.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/19.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/20.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/21.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/22.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/23.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/24.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/25.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/26.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/27.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/28.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/29.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/30.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/31.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/32.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/33.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/34.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/35.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/36.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/37.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/38.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/39.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/40.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/41.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/42.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/43.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/44.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/45.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/46.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/47.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/48.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/49.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/50.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/51.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/52.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/53.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/54.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/55.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/56.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/57.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/58.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/59.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/60.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/61.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/62.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/63.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/64.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/65.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/66.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/67.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/68.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/69.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/70.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/71.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/72.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/73.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/74.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/75.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/76.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/77.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/78.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/79.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/80.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/81.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/82.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/83.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/84.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/85.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/86.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/87.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/88.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/89.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/90.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/91.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/92.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/93.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/94.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/95.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/96.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/97.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/98.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/99.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/100.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/101.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/102.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/103.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/104.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/105.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/106.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/107.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/108.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/109.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/110.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/111.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/112.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/113.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/114.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/115.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/116.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/117.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/118.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/119.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/120.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/121.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/122.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/123.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/124.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/125.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/126.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/127.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/128.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/129.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/130.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/131.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/132.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/133.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/134.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/135.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/136.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/137.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/138.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/139.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/140.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/141.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/142.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/143.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/144.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/145.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/146.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/147.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/148.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/149.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/150.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/151.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/152.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/153.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/154.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/155.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/156.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/157.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/158.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/159.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/160.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/161.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/162.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/163.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/164.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/165.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/166.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/167.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/168.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/169.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/170.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/171.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/172.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/173.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/174.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/175.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/176.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/177.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/178.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/179.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/180.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/181.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/182.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/183.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/184.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/185.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/186.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/187.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/188.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/189.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/190.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/191.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/192.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/193.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/194.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/195.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/196.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/197.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/198.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/qg/20220926/199.txt'

# Load labeled data
n_train: 1000000
n_val: 200000
n_test: 200000
balance_samples: False

# Select model: pfn, efn, efp_linear, efp_lasso, efp_dnn
models: [pfn]

# efp parameters
dmax: 5                                             # maximal degree of the EFPs
efp_measure: 'hadr'                                 # 
efp_beta: 0.5                                       # Exponent of the pairwise distance

efp_dnn:                    

    learning_rate: [0.1, 0.01, 1.e-3, 1.e-4]    # (0.0001 cf 1810.05165)
    loss: 'binary_crossentropy'                     # loss function - use categorical_crossentropy instead ?
    metrics: ['accuracy']                           # measure accuracy during training
    batch_size: 1000                    
    epochs: 10                                      # number of training epochs

pfn:

    # Network architecture parameters
    Phi_sizes: [100, 100, 256]
    F_sizes: [100, 100, 100]
    #Phi_sizes: [200, 200, 200, 200, 512]
    #F_sizes: [200, 200, 200, 200, 200, 200]

    # Network training parameters
    epochs: 10
    batch_size: 500

    # Train PFNs for each of the following options
    pid: True
    nopid: True      
    charge: True
    
efn:

    # Network architecture parameters
    Phi_sizes: [100, 100, 256]
    F_sizes: [100, 100, 100]

    # Network training parameters
    learning_rate: 0.001
    epochs: 10
    batch_size: 500