# Config file for event classification
event_type: 'photoproduction'
classification_type: 'event'
classes: 'qq --> qq__gg --> gg' # The double underscore specifies the two classes to consider

n_jets_max: 10
n_particles_per_jet_max: 50
jet_pt_min_list: [3.]    # Can loop over different min jet pt 
min_particle_pt: 0.
kappa: [0.3, 0.5, 0.7]

# Input files of training data
input_files:
 - '/rstorage/ml-eic-flavor/qg/20220912/photoproduction_resolved.txt'

# Load labeled data
n_train: 100
n_val: 20
n_test: 20
balance_samples: True

# Select model: pfn, efn, efp_linear, efp_lasso, efp_dnn
models: [pfn]

pfn:

    # Network architecture parameters
    Phi_sizes: [100, 100, 256]
    F_sizes: [100, 100, 100]
    #Phi_sizes: [200, 200, 200, 200, 512]
    #F_sizes: [200, 200, 200, 200, 200, 200]

    # Network training parameters
    epochs: 10
    batch_size: 500
    use_pids: True