# Config file for u vs. d jet classification
event_type: 'dis'
classification_type: 'jet'
classes: 'u__d' # The double underscore specifies the two classes to consider

jet_pt_min_list: [10]     # Can loop over different min jet pt 
particle_input: ['out']    # Loop over different sets of input particles: in-jet, out-of-jet, or both
kappa: [0.3, 0.5, 0.7]

# Train multiple models with different particle min pt (in GeV) (only implemented for PFNs and single jet observables)
particle_pt_min_list: [0, 0.2, 0.4]

# Input files of training data
# 200 files, 1M DIS events each
# Rough flavor proportions -- 1s : 2c : 5d : 25u
input_files:
 #- '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20220912/test.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/0.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/1.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/2.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/3.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/4.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/5.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/6.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/7.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/8.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/9.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/10.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/11.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/12.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/13.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/14.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/15.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/16.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/17.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/18.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/19.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/20.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/21.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/22.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/23.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/24.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/25.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/26.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/27.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/28.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/29.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/30.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/31.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/32.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/33.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/34.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/35.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/36.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/37.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/38.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/39.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/40.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/41.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/42.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/43.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/44.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/45.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/46.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/47.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/48.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/49.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/50.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/51.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/52.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/53.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/54.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/55.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/56.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/57.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/58.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/59.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/60.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/61.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/62.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/63.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/64.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/65.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/66.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/67.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/68.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/69.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/70.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/71.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/72.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/73.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/74.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/75.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/76.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/77.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/78.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/79.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/80.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/81.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/82.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/83.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/84.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/85.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/86.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/87.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/88.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/89.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/90.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/91.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/92.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/93.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/94.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/95.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/96.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/97.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/98.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/99.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/100.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/101.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/102.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/103.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/104.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/105.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/106.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/107.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/108.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/109.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/110.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/111.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/112.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/113.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/114.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/115.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/116.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/117.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/118.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/119.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/120.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/121.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/122.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/123.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/124.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/125.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/126.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/127.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/128.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/129.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/130.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/131.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/132.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/133.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/134.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/135.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/136.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/137.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/138.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/139.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/140.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/141.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/142.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/143.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/144.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/145.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/146.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/147.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/148.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/149.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/150.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/151.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/152.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/153.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/154.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/155.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/156.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/157.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/158.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/159.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/160.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/161.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/162.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/163.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/164.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/165.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/166.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/167.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/168.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/169.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/170.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/171.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/172.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/173.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/174.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/175.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/176.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/177.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/178.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/179.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/180.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/181.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/182.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/183.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/184.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/185.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/186.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/187.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/188.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/189.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/190.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/191.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/192.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/193.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/194.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/195.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/196.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/197.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/198.txt'
 - '/global/cfs/cdirs/alice/jdmull/ml-eic-flavor/uds/20221003/199.txt'

# Load labeled data
n_train: 2500000
n_val: 500000
n_test: 500000
balance_samples: False

# Select model: pfn, efn, efp_linear, efp_lasso, efp_dnn
models: [pfn]

# efp parameters
dmax: 5                                             # maximal degree of the EFPs
efp_measure: 'hadr'                                 # 
efp_beta: 0.5                                       # Exponent of the pairwise distance

efp_dnn:                    

    learning_rate: [0.1, 0.01, 1.e-3, 1.e-4]    # (0.0001 cf 1810.05165)
    loss: 'binary_crossentropy'                     # loss function - use categorical_crossentropy instead ?
    metrics: ['accuracy']                           # measure accuracy during training
    batch_size: 1000                    
    epochs: 10                                      # number of training epochs

efp_linear:

    # Model hyperparameters -- SGDClassifier
    sgd_loss: 'hinge'                               # cost function
    sgd_penalty: ['l2', 'l1']                       # regularization term
    sgd_alpha: [1e-5, 1e-4, 1e-3]                   # regularization strength
    sgd_max_iter: 1000                              # max number of epochs
    sgd_tol: [1e-5, 1e-4, 1e-3]                     # criteria to stop training
    sgd_learning_rate: 'optimal'                    # learning schedule (learning rate decreases over time in proportion to alpha)
    sgd_early_stopping: False                       # whether to stop training based on validation score

    lda_tol: [1e-6, 1e-5, 1e-4, 1e-3, 5e-3]   # criteria to stop training

    # Hyperparameter tuning
    n_iter: 10                                      # number of random hyperparameter sets to try
    cv: 5                                           # number of cross-validation folds

efp_lasso:

    # Set d value to train Lasso on
    d_lasso: 4

    alpha: [1.e-4, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008, 0.0009, 0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009, 0.01, 0.05, 0.1]   # Constant multiplying the L1 term
    max_iter: 10000                                 # max number of epochs
    tol: 1e-6                                       # criteria to stop training

pfn:

    # Network architecture parameters
    Phi_sizes: [100, 100, 256]
    F_sizes: [100, 100, 100]
    #Phi_sizes: [200, 200, 200, 200, 512]
    #F_sizes: [200, 200, 200, 200, 200, 200]

    # Network training parameters
    epochs: 10
    batch_size: 500

    # Train PFNs for each of the following options
    pid: True
    nopid: True      
    charge: True
    
efn:

    # Network architecture parameters
    Phi_sizes: [100, 100, 256]
    F_sizes: [100, 100, 100]

    # Network training parameters
    learning_rate: 0.001
    epochs: 10
    batch_size: 500